apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql-secret
  namespace: moisture-monitoring
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: MOISTURE_SENSOR_PSQL_PASSWORD
      metadataPolicy: None
    secretKey: password
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    template:
      data: 
        username: moisture_user
        password: "{{ .password }}"
    creationPolicy: Owner
    deletionPolicy: Retain
    name: postgresql-secret
