apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: moisture-monitoring

resources:
  - namespace.yaml
  - postgresql-statefulset.yaml
  - influxdb-statefulset.yaml
  - orchestrator-deployment.yaml
  - api-server-deployment.yaml

# Uncomment after creating secrets.yaml from secrets-example.yaml
# - secrets.yaml
