apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pull-secret
  namespace: moisture-monitoring
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: MOISTURE_SENSOR_DOCKERCONFIGJSON
      metadataPolicy: None
    secretKey: dockerconfigjson
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-secretstore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson }}"
    creationPolicy: Owner
    deletionPolicy: Retain
    name: pull-secret
